# Generated by Django 2.1.7 on 2020-03-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopapp.Book')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshopapp.User')),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
