# Generated by Django 2.1.7 on 2020-03-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshopapp', '0004_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
    ]
